MCF: apply format to clang-format-all script

diff --git a/bin/clang-format-all b/bin/clang-format-all
--- a/bin/clang-format-all
+++ b/bin/clang-format-all
@@ -17,12 +17,12 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 function usage {
-    echo "Usage: $0 DIR..."
-    exit 1
+  echo "Usage: $0 DIR..."
+  exit 1
 }
 
 if [ $# -eq 0 ]; then
-    usage
+  usage
 fi
 
 # Variable that will hold the name of the clang-format command
@@ -33,52 +33,52 @@ FMT=""
 # that's present, otherwise we work backwards from highest version to lowest
 # version.
 for clangfmt in clang-format{,-{4,3}.{9,8,7,6,5,4,3,2,1,0}}; do
-    if which "$clangfmt" &>/dev/null; then
-        FMT="$clangfmt"
-        break
-    fi
+  if which "$clangfmt" &>/dev/null; then
+    FMT="$clangfmt"
+    break
+  fi
 done
 
 # Check if we found a working clang-format
 if [ -z "$FMT" ]; then
-    echo "failed to find clang-format"
-    exit 1
+  echo "failed to find clang-format"
+  exit 1
 fi
 
 # Check all of the arguments first to make sure they're all directories
 for dir in "$@"; do
-    if [ ! -d "${dir}" ]; then
-        echo "${dir} is not a directory"
-        usage
-    fi
+  if [ ! -d "${dir}" ]; then
+    echo "${dir} is not a directory"
+    usage
+  fi
 done
 
 # Find a dominating file, starting from a given directory and going up.
 find-dominating-file() {
-    if [ -r "$1"/"$2" ]; then
-        return 0
-    fi
-    if [ "$1" = "/" ]; then
-        return 1
-    fi
-    find-dominating-file "$(realpath "$1"/..)" "$2"
-    return $?
+  if [ -r "$1"/"$2" ]; then
+    return 0
+  fi
+  if [ "$1" = "/" ]; then
+    return 1
+  fi
+  find-dominating-file "$(realpath "$1"/..)" "$2"
+  return $?
 }
 
 # Run clang-format -i on all of the things
 for dir in "$@"; do
-    pushd "${dir}" &>/dev/null
-    if ! find-dominating-file . .clang-format; then
-        echo "Failed to find dominating .clang-format starting at $PWD"
-        continue
-    fi
-    find . \
-         \( -name '*.c' \
-         -o -name '*.cc' \
-         -o -name '*.cpp' \
-         -o -name '*.h' \
-         -o -name '*.hh' \
-         -o -name '*.hpp' \) \
-         -exec "${FMT}" -i '{}' \;
-    popd &>/dev/null
+  pushd "${dir}" &>/dev/null
+  if ! find-dominating-file . .clang-format; then
+    echo "Failed to find dominating .clang-format starting at $PWD"
+    continue
+  fi
+  find . \
+    \( -name '*.c' \
+    -o -name '*.cc' \
+    -o -name '*.cpp' \
+    -o -name '*.h' \
+    -o -name '*.hh' \
+    -o -name '*.hpp' \) \
+    -exec "${FMT}" -i '{}' \;
+  popd &>/dev/null
 done
