MCF: rename git-remove-submodule.sh to git-rm-submodule

diff --git a/bin/git-rm-submodule b/bin/git-rm-submodule
--- a/bin/git-rm-submodule
+++ b/bin/git-rm-submodule
@@ -1,13 +1,14 @@
-#!/bin/bash -e
+#!/usr/bin/env bash
+
 ## Remove the submodule
 ## Usage: git rm-submodule [ --no-commit ] dir
-## does not commit if --no-commit is given 
+## does not commit if --no-commit is given
 
 ## Script comes from https://github.com/kollerma/git-submodule-tools
 
 ## read input, display help if necessary
 if [[ "$@" == "" || "$@" == *--help* ]]; then
-    cat<<EOF
+  cat <<EOF
  Remove a submodule
 
  This command removes the submodule <directory> and creates a new commit
@@ -19,34 +20,34 @@ if [[ "$@" == "" || "$@" == *--help* ]]; then
 
     --no-commit: do not commit the result
 EOF
-    exit 0;
+  exit 0
 fi
 
 if [ "$1" == "--no-commit" ]; then
-    nocommit=1
-    dir=$2
-else 
-    dir=$1
+  nocommit=1
+  dir=$2
+else
+  dir=$1
 fi
 
 ## check if this is a valid submodule
 if [[ ! "$dir" || $(git ls-files --error-unmatch --stage -- "$dir" | grep -E '^160000') == "" ]]; then
-    echo >&2 "Error: \"$dir\" is not a submodule."
-    exit 1
+  echo >&2 "Error: \"$dir\" is not a submodule."
+  exit 1
 fi
 
 ## get the full path of the submodule
 dir=$(git ls-files --full-name "$dir")
 ## ensure that we are in the toplevel directory
 cdup=$(git rev-parse --show-toplevel) &&
-cd "$cdup" || {
-    echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
-    exit 1
+  cd "$cdup" || {
+  echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
+  exit 1
 }
 
 ## seems we're safe, so start removing
 ## get submodule url
-url=`git config --get submodule."$dir".url || echo "unknown"`
+url=$(git config --get submodule."$dir".url || echo "unknown")
 ## remove config entries
 git config -f .gitmodules --remove-section submodule."$dir" 2>/dev/null || echo -n ""
 git config --remove-section submodule."$dir" 2>/dev/null || echo -n ""
@@ -54,6 +55,6 @@ git rm --cached "$dir"
 rm -rf "$dir"
 ## commit changes
 if [[ ! "$nocommit" ]]; then
-    git add .gitmodules
-    git commit -m "Removed submodule \"$dir\" (url: $url)"
+  git add .gitmodules
+  git commit -m "Removed submodule \"$dir\" (url: $url)"
 fi
