feat(neovim): do not fail entire post-install if plugin restoration failed

diff --git a/misc/packages/neovim/post-install b/misc/packages/neovim/post-install
--- a/misc/packages/neovim/post-install
+++ b/misc/packages/neovim/post-install
@@ -14,4 +14,6 @@ pip install --upgrade pynvim
 fnm exec --using=node-nvim npm install --location=global neovim
 
 # Ensure that plugins are installed
-nvim-sync restore
+if ! nvim-sync restore; then
+  echo "Failed to install Neovim plugins, run 'nvim-sync restore' manually to retry"
+fi
