Git: add gh-fzf extension

diff --git a/misc/packages/gh/post-install b/misc/packages/gh/post-install
--- a/misc/packages/gh/post-install
+++ b/misc/packages/gh/post-install
@@ -1,12 +1,18 @@
 #!/usr/bin/env bash
 
-echo "Installing copilot extension for gh..."
-if ! gh extension install --force github/gh-copilot; then
-  echo "Failed to install gh-copilot extension"
-  echo "This is likely because gh config file was not decrypted"
-  echo "Repeat installation once the file is decrypted"
-  exit 0
-fi
+install_extension() {
+  local extension=$1
+  echo "Installing $extension extension for gh..."
+  if ! gh extension install --force "$extension"; then
+    echo "Failed to install $extension extension"
+    echo "This is likely because gh config file was not decrypted"
+    echo "Repeat installation once the file is decrypted"
+    exit 0
+  fi
+}
+
+install_extension "github/gh-copilot"
+install_extension "benelan/gh-fzf"
 
 echo "Creating aliases for copilot commands..."
 ALIASES=$HOME/.local/bash/72-gh-copilot.bash
