MCF: improve 'smi' command to handle Ninja projects

diff --git a/scripts/bin/smi b/scripts/bin/smi
--- a/scripts/bin/smi
+++ b/scripts/bin/smi
@@ -2,10 +2,18 @@
 
 orphans=`chkstow -a -t /usr/local | wc -l`
 if [[ $orphans -gt 0 ]]; then
-  echo "There are orphans, please stow them first!"
+  echo "There are orphans in /usr/local, please stow them first!"
   exit 1
 fi
 
 sudo make install
+
+if [[ $? -eq 2 ]]; then
+  # Failed with "no rule to make target install".
+  # Try to compile using Ninja. A caveat here is that we will invoke
+  # with sudo, and a Nix-installed Ninja may not be in the path.
+  ninja=`which ninja`
+  sudo $ninja install
+fi
 
 echo -e "\e[91mDo not forget to stow the newly installed files!\e[39m"
